name: Glyphwords
main: me.alchemi.glyphwords.Glyph
authors:
- Alchemi
version: ${project.version}
api-version: 1.15
description: Adds custom enchantments meant for a Kingdom server.
depend:
- AlchemicLibrary
commands:
  giveenchant:
    permission: glyphwords.enchant.give
    description: Give enchanted book to player
    usage: /giveenchant <player> <enchant>
    
permissions:
  glyphwords.enchant.give:
    default: op